# Generated by Django 4.2.9 on 2026-09-17 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('star', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_type', models.CharField(choices=[('calorie', 'Calorie calculator'), ('macro', 'Macro calculator')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('activity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('calories', models.PositiveIntegerField()),
                ('protein_grams', models.PositiveIntegerField()),
                ('carbohydrate_grams', models.PositiveIntegerField()),
                ('fat_grams', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
