# Generated by Django 4.2.9 on 2026-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star', '0007_plan_paymentorder_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
